{% set name = "ujson" %}
{% set version = "5.11.0" %}
{% set sha256 = "e204ae6f909f099ba6b6b942131cee359ddda2b6e4ea39c12eb8b991fe2010e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4
  run:
    - python

test:
  imports:
    - ujson

about:
  home: https://github.com/ultrajson/ultrajson
  summary: Ultra fast JSON decoder and encoder written in C with Python bindings
  license: BSD-3-Clause
  license_file: LICENSE.txt

  dev_url: https://github.com/ultrajson/ultrajson

extra:
  recipe-maintainers:
    - kszucs
    - synapticarbors
