{% set name = "ujson" %}
{% set version = "5.7.0" %}
{% set sha256 = "e788e5d5dcae8f6118ac9b45d0b891a0d55f7ac480eddcb7f07263f2bcf37b23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python

test:
  imports:
    - ujson

about:
  home: https://github.com/ultrajson/ultrajson
  summary: Ultra fast JSON decoder and encoder written in C with Python bindings
  license: BSD-3-Clause
  license_file: LICENSE.txt

  dev_url: https://github.com/ultrajson/ultrajson

extra:
  recipe-maintainers:
    - kszucs
    - synapticarbors
