schema_version: 1

context:
  name: ujson
  version: "6.0.0"
  sha256: 80e23393feb707582e0ad495c397a4477b646d08094d2df64f7316f9fafd8aae

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 80e23393feb707582e0ad495c397a4477b646d08094d2df64f7316f9fafd8aae

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=77
    - setuptools_scm >=3.4
  run:
    - python

tests:
  - python:
      imports:
        - ujson
      pip_check: true

about:
  summary: Ultra fast JSON decoder and encoder written in C with Python bindings
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/ultrajson/ultrajson
  repository: https://github.com/ultrajson/ultrajson

extra:
  recipe-maintainers:
    - thewchan
    - kszucs
    - synapticarbors
