appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hUl9CXpCey47XlqUr7GkEPC3Ec47+HwiC3v2hHOl69oD7dRs9brGCZvsLYt7jybeJ/iwqfITrZoL33kfx4zXDIwPBXOTTPKagRLB+38XRKmE+CZpUE0gxSRLrVL36vNSm9VLlKvmiXmyRntdwxF5lPvB5dm5b4NU/UqYSV3aI7lwuXXUU3LkvX+ZRYYrQm/smcb0hPukJHoxuHypfpG9+zQxC58ejS+8X95J9AzeQ6ApOipgskOIj6GTwt+4aMe5cvhmD5ltYHCQEaw3Wc0u6UfraJkFcawHYG7Pqjk87WZZyIFtE1lI/pxYsVLtFAGlLwTPc5APInPx/fw7dSSc3yhrlXZtGGfTOw1T318ngAKKv+gl3mNF61572xBP4+lwk+5NaLyMm8l8DzgX0Qo4R+yAgiSbBwUsY2FN4xNydn2RR7k5IHnBM1OvcopOVDjW9RR7V2cKyhEelsZJvUhv/awBPQDUa+wko6ZLMVcSKctiRhqIBSXfFy1Z651cImH84pdnBKJGXVMUBgDANAbsyJMAyCsrsGvCCdFbR3hNYhZlW4B9PG2NeOXGr7KRIR9FcKfUu2AgAmuoCnDL7K7lExICpji7xO3t6X4g4PKKTStyGELAHk/AASPzis8gA019W46jyzAhw27cUcxA/juQXB35AcektNqpRLZ3CLj+FDI=}
